title: "HI I'M ANDYMION"
first_name: Andy
last_name: Mion
description: "로보틱스 AI·비전에 관심이 많은 김민규입니다"
email: "kmk4729@naver.com"
github_username: "kmk4729"
footer_text: "Powered by Jekyll with Creative Theme. <br>Contact: <a href='mailto:kmk4729@naver.com'>kmk4729@naver.com</a>"
lang: "ko"
icon: "🤖"

url: "https://kmk4729.github.io"
baseurl: ""

navbar_fixed: true
footer_fixed: true
search_enabled: true
enable_darkmode: true
enable_math: true

blog_name: "KMK4729 Blog"
blog_description: "알고리즘·프로젝트·실험·리뷰 기록"
permalink: /blog/:year/:title/

plugins:
  - jekyll-feed
  - jemoji
  - jekyll-github-metadata

repository: kmk4729/kmk4729.github.io


markdown: kramdown
highlighter: rouge

imagemagick:
  enabled: true
  widths: [480, 800, 1400]
  input_directories: [assets/img/]

exclude: ["bin/", "README.md", "LICENSE"]
