title: "KMK4729"
description: "SSAFY Embedded · Computer Vision"
url: "https://kmk4729.github.io"
baseurl: ""
repository: kmk4729/kmk4729.github.io
github_username: "kmk4729"
email: "kmk4729@naver.com"
lang: "ko"
timezone: Asia/Seoul

theme: jekyll-theme-chirpy

plugins:
  - jekyll-feed
  - jemoji
  - jekyll-github-metadata

markdown: kramdown
highlighter: rouge

exclude: ["bin/", "README.md", "LICENSE"]